import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Contact New Site',
    description: 'Contact Generated by coffe67',
}

export default function ContactPage(){
    return (
        <>
        <span>Contact Page</span>
        </>
    )
}